In [1]:
import numpy as np
A = np.array([[-2.,0.],[1.,-10.]])
print(A)
A.dtype

[[ -2.   0.]
 [  1. -10.]]


dtype('float64')

In [2]:
#HW 3 essential code

import numpy as np
import sympy as sym

q, v, tau = sym.symbols('q, v, tau')

f = sym.Matrix([[v], [2 * sym.cos(q) + 3*tau]]) #bracket form is [q,v] --> [qdot,vdot]

q_e = np.pi
v_e = 0.
tau_e = 2./3.


f_num = sym.lambdify((q, v, tau), f)
f_num(q_e, v_e, tau_e)
f.jacobian([q, v])

# Create lambda function
A_num = sym.lambdify((q, v, tau), f.jacobian([q, v]))

# Evaluate lambda function at equilibrium point
A = A_num(q_e, v_e, tau_e)

# Suppress the use of scientific notation when printing small numbers
#np.set_printoptions(suppress=True)

# Create lambda functions
B_num = sym.lambdify((q, v, tau), f.jacobian([tau]))

# Evaluate lambda function at equilibrium point
B = B_num(q_e, v_e, tau_e)


# Make sure A and B have floating-point numbers inside
A = A.astype(float)
B = B.astype(float)

# Print the resulting values
print(A)
print(B)

print(A.tolist())
print(B.tolist())


[[ 0.0000000e+00  1.0000000e+00]
 [-2.4492936e-16  0.0000000e+00]]
[[0.]
 [3.]]
[[0.0, 1.0], [-2.4492935982947064e-16, 0.0]]
[[0.0], [3.0]]


In [3]:
import numpy as np
import sympy as sym

g, m, r = sym.symbols('g, m, r')

f = sym.Matrix([[(r/5)-(4*g/5)-(2*m)-(m**3)], [g]]) #bracket form is [q,v] --> [qdot,vdot]

g_e = 0.
m_e = 2.
r_e = 60.


f_num = sym.lambdify((g, m, r), f)
f_num(g_e, m_e, r_e)
f.jacobian([g, m])

# Create lambda function
A_num = sym.lambdify((g, m, r), f.jacobian([g, m]))

# Evaluate lambda function at equilibrium point
A = A_num(g_e, m_e, r_e)

# Suppress the use of scientific notation when printing small numbers
#np.set_printoptions(suppress=True)

# Create lambda functions
B_num = sym.lambdify((g, m, r), f.jacobian([r]))

# Evaluate lambda function at equilibrium point
B = B_num(g_e, m_e, r_e)


# Make sure A and B have floating-point numbers inside
A = A.astype(float)
B = B.astype(float)

# Print the resulting values
#print(A)
#print(B)

print(A.tolist())
print(B.tolist())


[[-0.8, -14.0], [1.0, 0.0]]
[[0.2], [0.0]]


In [4]:
import numpy as np

L = np.array([[0., 1.], [-3., 2.]])
M = np.array([[2., 0.], [-1., 1.]])
N = np.array([[-1.], [4.]])

L + M
L - M

M.T #transpose
M @ N #matrix math

from scipy import linalg
linalg.expm(M)

#x = e^ft * x0

x = linalg.expm(F*t)*x0
print(x)



NameError: name 'F' is not defined

In [ ]:
L = sym.nsimplify(L, rational=True)
M = sym.nsimplify(M, rational=True)
N = sym.nsimplify(N, rational=True) #simplifying float numbers



In [ ]:
import math as m
import numpy as np
import sympy as sym
# Description of system and initial condition (do not change)
F = np.array([[0, 1], [4, 3]])
x0 = np.array([[-1], [2]])

# Convert F and x0 to SymPy matrices with rational elements
F = sym.Matrix(F)
#F = sym.nsimplify(F, rational=True)
x0 = sym.Matrix(x0)
#x0 = sym.nsimplify(x0, rational=True)

# Create a symbol to represent time
t = sym.symbols('t')

# Compute solution as a function of time (symbolic)
x_sym = sym.exp(F * t).simplify()*x0

print(x_sym)

In [ ]:
#hw 4.2
import numpy as np

A = np.array([[ 8,  8,  8], [ 5, -7, -9], [-6,  4,  0]])
B = np.array([[ 2,  1], [ 8, -1], [ 5,  4]])
C = np.array([[1, 2, 6]])
D = np.array([[0, 0]])
K = np.array([[-2, -8, -5], [-4, -2, -3]])

A = sym.Matrix(A)
B = sym.Matrix(B)
C = sym.Matrix(C)
D = sym.Matrix(D)
K = sym.Matrix(K)

F = A-B@K
print(F)

G = C-D@K
print(G)

In [ ]:
#HW 4.3
import numpy as np

A = np.array([[-0.7, -0.3], [-0.8, -0.6]])
B = np.array([[-0.2], [-0.3]])
C = np.array([[-0.2, 0.8]])
D = np.array([[0.0]])
K = np.array([[0.3, -0.9]])
t0 = 0.9
x0 = np.array([[-0.6], [-0.3]])
t1 = 1.0

A = sym.Matrix(A)
B = sym.Matrix(B)
C = sym.Matrix(C)
D = sym.Matrix(D)
K = sym.Matrix(K)
x0 = sym.Matrix(x0)

F = A-B@K
#print(F)

def x(t):
    return sym.exp(F * (t-t0)).simplify()@x0
print(x(t1))

def y(t):
    return C@sym.exp(F * (t-t0)).simplify()@x0

print(y(t1))

In [ ]:
#HW 4.4
import math as m
import numpy as np
import sympy as sym


A = np.array([[ 0,  1], [ 4, 10]])
B = np.array([[0], [1]])
C = np.array([[0, 1]])
D = np.array([[0]])
K = np.array([[24, 18]])
x0 = np.array([[1], [0]])

A = sym.Matrix(A)
B = sym.Matrix(B)
C = sym.Matrix(C)
D = sym.Matrix(D)
K = sym.Matrix(K)
x0 = sym.Matrix(x0)

F = A-B@K
#print(F)
t = sym.symbols('t')

x = sym.exp(F*t)@x0
u = -K@x

y = C@x+D@u
y,
print(y)

In [ ]:
#HW4.5
import numpy as np

W = np.array([[-0.6, 0.7, 0.0, 0.7], [0.7, 0.0, -0.4, -0.8], [-0.4, 0.3, -0.1, -0.1], [0.3, -0.7, -0.6, 0.0]])

from mpmath import nsum, exp, inf
nsum(lambda x: (1/m.factorial(k)), [-inf, inf])
mpf('1.7726372048266521')

In [ ]:
#HW 4.6

import numpy as np

A = np.array([[0.90000000, 0.30000000, -0.90000000], [0.90000000, 0.70000000, -0.40000000], [-0.50000000, 0.50000000, 0.00000000]])
M = np.array([[1.34812925, 0.09137121, -0.31871547], [0.35641466, 1.23677254, -0.17758059], [-0.14963047, 0.16024996, 1.01082967]])

A = sym.Matrix(A)
M = sym.Matrix(M)



In [ ]:
#HW 5 EIGEN PRACTICE
import numpy as np
from scipy import linalg

A = np.array([[0., 1.], [0., 0.]])
B = np.array([[0.], [1.]])
K = np.array([[29., 10.]])

# Description of closed-loop system (2D numpy array)
F = A - B@K

# Eigenvalues of closed-loop system (1D numpy array)
s = linalg.eigvals(F)
print(s)
print((s.real < 0).all())

In [ ]:
#HW 5.1

import numpy as np

A = np.array([[-0.9, 0.8, 0.5], [0.6, -0.7, -0.9], [-0.3, 0.7, -0.8]])
B = np.array([[0.1], [-0.6], [-0.5]])
C = np.array([[0.1, -0.6, -0.9]])
D = np.array([[0.0]])
K1 = np.array([[-3557.5, -2784.3, 2578.4]])
K2 = np.array([[-70.0, -43.5, 18.4]])
K3 = np.array([[-3.7, 79.7, -63.6]])
K4 = np.array([[-320.5, -232.3, 236.1]])
K5 = np.array([[-2767.9, -2218.4, 2078.9]])

# Description of closed-loop system (2D numpy array)
F1 = A - B@K1
F2 = A - B@K2
F3 = A - B@K3
F4 = A - B@K4
F5 = A - B@K5
# Eigenvalues of closed-loop system (1D numpy array)
s1 = linalg.eigvals(F1)
s2 = linalg.eigvals(F2)
s3 = linalg.eigvals(F3)
s4 = linalg.eigvals(F4)
s5 = linalg.eigvals(F5)

print((s1.real < 0).all())
print((s2.real < 0).all())
print((s3.real < 0).all())
print((s4.real < 0).all())
print((s5.real < 0).all())

In [ ]:
# The matrix to diagonalize (do not change)
G = np.array([[1.5, 8.5], [-2.5, -7.5]])

s = np.diag(G)
# The invertible matrix V (2D numpy array)
V = np.diag(G)

# The diagonal matrix S (2D numpy array)
# S = ...

# Remember that you can use "print" statements to check your work.
print(s)

In [12]:
import numpy as np
from scipy import linalg

# Suppress the use of scientific notation when printing small numbers
np.set_printoptions(suppress=True)

F = np.array([[-2.0, 0.0], [3.0, -1.0]])

s = linalg.eigvals(F)
print(s)

s, V = linalg.eig(F)

print(V)
print(s)

s1 = s[0]
print(s1)

s2 = s[1]
print(s2)

v1 = V[:, 0]
print(v1)

v2 = V[:, 1]
print(v2)

print(F @ v1)
print(s1 * v1)

print(F @ v2)
print(s2 * v2)

[-1.+0.j -2.+0.j]
[[ 0.          0.31622777]
 [ 1.         -0.9486833 ]]
[-1.+0.j -2.+0.j]


In [ ]:
# The matrix to diagonalize (do not change)
G = np.array([[1.5, 8.5], [-2.5, -7.5]])

# The invertible matrix V (2D numpy array)
s,V = linalg.eig(G)

# The diagonal matrix S (2D numpy array)
S = np.diag(s)

In [28]:
import numpy as np

A = np.array([[0.8, 0.4, -0.4, -0.7], [-0.4, 0.7, 0.5, -0.6], [0.9, 0.7, 0.0, -0.9], [0.2, 0.9, -0.8, -0.9]])
B = np.array([[0.2], [0.1], [0.9], [0.6]])
C = np.array([[-6.0, -6.0, -2.0, 5.0]])
D = np.array([[0.0]])
K = np.array([[0.9, -0.4, -0.3, 0.5]])

F = A-B@K
print(F)

#G = C-D@K
#print(G)

s,V = linalg.eig(F)
print(V.tolist())
print("  ")
S = np.diag(s)

print(S.tolist())

[[ 0.62  0.48 -0.34 -0.8 ]
 [-0.49  0.74  0.53 -0.65]
 [ 0.09  1.06  0.27 -1.35]
 [-0.34  1.14 -0.62 -1.2 ]]
[[0.33845061551972955, -0.23493295158675598, -0.5576489144937113, 0.06533331426397086], [0.19276504798473387, -0.7560408825740325, 0.6804443635432413, -0.7412950025797495], [0.4809913511523175, -0.010297308463544324, 0.07855923806234923, -0.6339183696522805], [0.7854553693536173, -0.6108212975771389, 0.4688833569250265, -0.21061998436750728]]
  
[[(-1.4463993497782275+0j), 0j, 0j, 0j], [0j, (0.06980685582521234+0j), 0j, 0j], [0j, 0j, (0.7548582056305821+0j), 0j], [0j, 0j, 0j, (1.051734288322433+0j)]]


In [30]:
import numpy as np

F = np.array([[-9.0, 7.0], [-1.0, -3.0]])

print(linalg.det(F))
s,V = linalg.eig(F)
print(V.tolist())
print("  ")
S = np.diag(s)

print(S.tolist())

34.0
[[-0.975286862174966, -0.8458618108979595], [-0.2209423826903945, -0.533402096794177]]
  
[[(-7.414213562373095+0j), 0j], [0j, (-4.585786437626905+0j)]]


In [38]:
import numpy as np

A = np.array([[-7.0, -1.0], [-3.0, -5.0]])
B = np.array([[-8.0], [4.0]])
C = np.array([[2.0, -8.0]])
D = np.array([[0.0]])
K = np.array([[-5.0, 4.0]])
V = np.array([[3.0, -6.0], [-4.0, -8.0]])

G = (C-D@K)@V
print(G.tolist())

F = np.linalg.inv(V)@(A-B@K)@V
print(F.tolist())


[[38.0, 52.0]]
[[-61.04166666666666, -2.5833333333333357], [13.645833333333332, -6.958333333333336]]


In [2]:
import numpy as np

A = np.array([[0.20, 0.10], [0.80, -0.60]])
B = np.array([[0.70], [0.60]])
C = np.array([[-0.80, -0.20]])
D = np.array([[0]])
p = np.array([[-8.17, -3.58]])

K = p

F = A-B@K
print(F)

G = C-D@K
print(G)

[[5.919 2.606]
 [5.702 1.548]]
[[-0.8 -0.2]]


In [4]:
import numpy as np
from scipy import signal

A = np.array([[0.20, 0.10], [0.80, -0.60]])
B = np.array([[0.70], [0.60]])
C = np.array([[-0.80, -0.20]])
D = np.array([[0]])
p = np.array([[-8.17, -3.58]])

#find k
fbk = signal.place_poles(A,B,[-8.17, -3.58])
K = fbk.gain_matrix
print(K.tolist())


[[-633.7580000000157, 758.3010000000185]]


In [1]:
import numpy as np

A = np.array([[ 0,  5, -3,  5], [-3, -2, -1,  5], [ 3, -5, -3, -1], [ 3,  4,  0, -3]])

a = np.poly(A)[1:]
print(a.tolist())


[7.999999999999996, 4.999999999999986, 34.99999999999983, -32.99999999999986]


In [4]:
import numpy as np

A = np.array([[-0.4, -0.9, -0.3], [-0.7, 0.7, 0.2], [0.4, 0.5, 0.6]])
B = np.array([[0.6], [0.3], [-0.2]])

#r = np.poly(p)[1:].real

a = np.poly(A)[1:]

Accf = np.block([[-a], [np.eye(2), np.zeros((2, 1))]]) 
Bccf = np.block([[1.], [np.zeros((2, 1))]])

# Accf = np.block([[-a], [np.eye(n-1), np.zeros((n*1, 1))]]) 
# Bccf = np.block([[1.], [np.zeros((n-1, 1))]])


print(Accf.tolist())
print(Bccf.tolist())

[[0.9000000000000012, 0.7099999999999986, -0.38899999999999996], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]
[[1.0], [0.0], [0.0]]


In [7]:
import numpy as np

A = np.array([[4.0, -4.0], [1.0, 0.0]])
B = np.array([[1.0], [0.0]])
r = np.array([[9.0, 20.0]])

a = np.poly(A)[1:]

Kccf = (r - a).reshape([1, -1])
print(Kccf.tolist())

[[13.0, 16.0]]


In [17]:
############################################################################
#acker
############################################################################
def acker(A, B, p):
    """
    INPUTS
    - A and B are 2d numpy arrays that describe a state-space system
    - p is a list of desired eigenvalue locations
    OUTPUTS
    - K, a 2d numpy array, is a gain matrix that would put closed-loop eigenvalues at p
    
    We assume that B has only one column (i.e., the system described by A and B
    has only one input) and that every complex number in p has a conjugate pair.
    """
    
    # Find the coefficients of the characteristic polynomial with roots at p
    r = np.poly(p)[1:].real
    
    # Find the coefficients of the characteristic polynomial of A
    a = np.poly(A)[1:]
    
    # Find the state space system (Accf, Bccf) that is equivalent to (A, B)
    # but that is in controllable canonical form
    Accf = np.block([[-a], [np.eye(A.shape[0]-1), np.zeros((A.shape[0]-1, 1))]])
    Bccf = np.block([[1.], [np.zeros((A.shape[0]-1, 1))]])
    
    # Find state feedback for (Accf, Bccf)
    Kccf = (r - a).reshape([1, -1])
    
    # Find the coordinate transformation between (Accf, Bccf) and (A, B)
    W = B
    n = A.shape[0]
    for i in range(1, n):
        col = np.linalg.matrix_power(A, i) @ B
        W = np.block([W, col])
    
    Wccf = Bccf
    n = A.shape[0]
    for i in range(1, n):
        col = np.linalg.matrix_power(Accf, i) @ Bccf
        Wccf = np.block([Wccf, col])
    
    inverse_of_V = Wccf @ linalg.inv(W)
    
    # Find and return state feedback for (A, B)
    K = Kccf @ inverse_of_V
    return K


In [33]:
import numpy as np

p = [5.0+0.0j, -5.0+0.0j, -3.0-2.0j, -3.0+2.0j, 4.0+0.0j]

r = np.poly(p)[1:].real
print(r.tolist())

# Find the coefficients of the characteristic polynomial of A
a = np.poly(A)[1:]
print(a.tolist())


[2.0, -36.0, -102.0, 275.0, 1300.0]
[-0.8999999999999999, -0.4800000000000014, 0.49700000000000133, -0.16050000000000061]


In [11]:
import numpy as np
from scipy import linalg

A = np.array([[0.1, 0.9, -0.7], [-0.5, 0.4, -0.5], [0.1, -0.6, 0.5]])
B = np.array([[0.6], [-0.5], [-0.7]])
F = np.array([[-4.1, 4.9, 3.0], [0.6, -0.0, -0.3], [-7.4, 7.2, 5.1]])
G = np.array([[2.7], [-0.8], [5.0]])

Accf = F
Bccf = G

Wccf = Bccf

n = A.shape[0]

W = B
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A, i) @ B
    W = np.block([W, col])

for i in range(1, n):
    col = np.linalg.matrix_power(Accf, i) @ Bccf
    Wccf = np.block([Wccf, col])

inverse_of_V = Wccf @ linalg.inv(W)

V = linalg.inv(inverse_of_V)

print(V.tolist())

[[-1.9999999999989404, 4.999999999998312, 1.9999999999991582], [-2.999999999999053, 2.999999999998505, 1.99999999999925], [0.99999999999946, -1.9999999999991394, -0.999999999999571]]


In [28]:
import numpy as np

A = np.array([[0.2, -0.5], [0.5, -0.2]])
B = np.array([[0.5], [0.7]])
F = np.array([[0.9, 0.6], [-1.7, -0.9]])
G = np.array([[0.2], [0.3]])
V = np.array([[1, 1], [2, 1]])
L = np.array([[ 2, -5]])

Accf = F
Bccf = G
Kccf = L

#print(acker(A,B,[3, 5]).tolist())

W = B
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A, i) @ B
    W = np.block([W, col])

Wccf = Bccf
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(Accf, i) @ Bccf
    Wccf = np.block([Wccf, col])

inverse_of_V = Wccf @ linalg.inv(W)


K = Kccf @ inverse_of_V
print(K.tolist())

[[-12.000000000000002, 7.000000000000002]]


In [31]:
import numpy as np

A = np.array([[0.2, 0.4, 0.2, 0.1], [-0.9, 0.2, 0.8, -0.8], [0.7, 0.4, -0.1, -0.7], [0.8, 0.1, -0.8, 0.6]])
B = np.array([[0.8], [-0.9], [-0.2], [-0.4]])
p = [-10.0+5.0j, -10.0-5.0j, -10.0+4.0j, -10.0-4.0j]

r = np.poly(p)[1:].real
print(r.tolist())

# Find the coefficients of the characteristic polynomial of A
a = np.poly(A)[1:]
print(a.tolist())

# Find the state space system (Accf, Bccf) that is equivalent to (A, B)
# but that is in controllable canonical form
Accf = np.block([[-a], [np.eye(A.shape[0]-1), np.zeros((A.shape[0]-1, 1))]])
Bccf = np.block([[1.], [np.zeros((A.shape[0]-1, 1))]])
print(Accf.tolist())
print(Bccf.tolist())

# Find state feedback for (Accf, Bccf)
Kccf = (r - a).reshape([1, -1])
print(Kccf.tolist())

# Find the coordinate transformation between (Accf, Bccf) and (A, B)
W = B
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A, i) @ B
    W = np.block([W, col])

Wccf = Bccf
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(Accf, i) @ Bccf
    Wccf = np.block([Wccf, col])

inverse_of_V = Wccf @ linalg.inv(W)
print(linalg.inv(inverse_of_V).tolist())

# Find and return state feedback for (A, B)
K = Kccf @ inverse_of_V


[40.0, 641.0, 4820.0, 14500.0]
[-0.8999999999999999, -0.4800000000000014, 0.49700000000000133, -0.16050000000000061]
[[0.8999999999999999, 0.4800000000000014, -0.49700000000000133, 0.16050000000000061], [1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0]]
[[1.0], [0.0], [0.0], [0.0]]
[[40.9, 641.48, 4819.503, 14500.1605]]
[[0.7999999999999995, -0.9999999999999978, -0.3370000000000045, 0.5109000000000032], [-0.8999999999999972, 0.06999999999999539, 1.2260000000000022, -0.3611999999999995], [-0.20000000000000262, 0.6800000000000015, -1.224999999999995, 0.7304999999999954], [-0.4000000000000016, 0.8300000000000005, -0.6469999999999955, 0.24599999999999578]]


In [5]:
import numpy as np
from scipy import linalg

A = np.array([[0, 1], [0, 0]])
B = np.array([[0], [1/15]])

W = B
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A, i) @ B
    W = np.block([W, col])
    
print(W.tolist())
print(np.linalg.matrix_rank(W))

[[0.0, 0.06666666666666667], [0.06666666666666667, 0.0]]
2


In [7]:
import numpy as np
from scipy import linalg

A = np.array([[0, 1, 0], [0, 0, 0], [0,0,0]])
B = np.array([[0], [1/15], [-1]])

W = B
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A, i) @ B
    W = np.block([W, col])
    
print(W.tolist())
print(np.linalg.matrix_rank(W))

[[0.0, 0.06666666666666667, 0.0], [0.06666666666666667, 0.0, 0.0], [-1.0, 0.0, 0.0]]
2


In [8]:
import numpy as np
from scipy import linalg

A = np.array([[0, 1, 0], [3*0.0011*0.0011*(5-15)/15, 0, 0], [0,0,0]])
B = np.array([[0], [1/15], [-1]])

W = B
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A, i) @ B
    W = np.block([W, col])
    
print(W.tolist())
print(np.linalg.matrix_rank(W))

[[0.0, 0.06666666666666667, 0.0], [0.06666666666666667, 0.0, -1.6133333333333335e-07], [-1.0, 0.0, 0.0]]
3


In [9]:
import numpy as np
from scipy import linalg

A1 = np.array([[2.0, -11.6, 42.2, 7.0], [14.5, -44.0, 164.5, 27.6], [22.7, -82.2, 304.0, 50.8], [-109.0, 425.0, -1566.5, -261.4]])
B1 = np.array([[0.2], [1.2], [1.8], [-8.9]])
A2 = np.array([[-6.5, -2.9, -0.4], [21.4, 9.5, 1.3], [-42.8, -19.0, -2.6]])
B2 = np.array([[0.5], [-1.6], [3.2]])
A3 = np.array([[-144.8, 52.9, 8.2, -8.5], [-693.3, 253.1, 39.4, -40.7], [-962.3, 352.5, 55.0, -56.9], [-2773.2, 1012.4, 157.6, -162.8]])
B3 = np.array([[-0.5], [-2.4], [-3.4], [-9.6]])
A4 = np.array([[-5.1, 0.5, -1.3, 1.1], [-24.0, 3.2, -5.1, 4.5], [62.9, -7.1, 15.0, -12.9], [62.9, -7.1, 15.0, -12.9]])
B4 = np.array([[-0.2], [-0.8], [2.3], [2.3]])
A5 = np.array([[0.3, -0.4, 1.8], [0.4, -0.9, 4.3], [0.0, 0.0, 0.0]])
B5 = np.array([[0.2], [0.5], [0.0]])

W1 = B1
n = A1.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A1, i) @ B1
    W1 = np.block([W1, col])
    
print(W1.tolist())
print(np.linalg.matrix_rank(W1))

print(" ")

W2 = B2
n = A2.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A2, i) @ B2
    W2 = np.block([W2, col])
    
print(W2.tolist())
print(np.linalg.matrix_rank(W2))

print(" ")

W3 = B3
n = A3.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A3, i) @ B3
    W3 = np.block([W3, col])
    
print(W3.tolist())
print(np.linalg.matrix_rank(W3))

print(" ")

W4 = B4
n = A4.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A4, i) @ B4
    W4 = np.block([W4, col])
    
print(W4.tolist())
print(np.linalg.matrix_rank(W4))

print(" ")

W5 = B5
n = A5.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A5, i) @ B5
    W5 = np.block([W5, col])
    
print(W5.tolist())
print(np.linalg.matrix_rank(W5))

[[0.2, 0.14000000000000412, -0.1400000000020034, -0.016799999995896542], [1.2, 0.5600000000000094, -0.5040000000121125, -0.043400000001838634], [1.8, 0.9800000000000466, -0.9659999999859892, -0.09240000000645665], [-8.9, -5.040000000000248, 5.026000000040369, 0.5026000000347324]]
4
 
[[0.5, 0.10999999999999943, -0.0009999999999934506], [-1.6, -0.34000000000000163, 0.007999999999984908], [3.2, 0.6800000000000033, -0.015999999999969816]]
2
 
[[-0.5, -0.8399999999999892, -0.5370000000036761, -0.06730000000651692], [-2.4, -4.029999999999916, -2.5710000000140383, -0.32020000002921734], [-3.4, -5.610000000000014, -3.565000000009036, -0.4378000000140787], [-9.6, -16.119999999999663, -10.284000000056153, -1.2808000001168693]]
3
 
[[-0.2, 0.16000000000000003, 0.027999999999997693, 0.012000000000001121], [-0.8, 0.8600000000000012, 0.15400000000001235, 0.05419999999997693], [2.3, -2.0699999999999985, -0.38900000000000645, -0.14909999999995005], [2.3, -2.0699999999999985, -0.38900000000000645, -0.

In [10]:
import numpy as np
from scipy import linalg

A = np.array([[5.00, 6.00, 0.00], [-3.00, -4.00, 0.00], [0.00, 0.00, -1.00]])
B = np.array([[1.00], [-1.00], [1.00]])
pdes = -2.00

W = B
n = A.shape[0]
for i in range(1, n):
    col = np.linalg.matrix_power(A, i) @ B
    W = np.block([W, col])
    
print(W.tolist())
print(np.linalg.matrix_rank(W))

[[1.0, -1.0, 1.0], [-1.0, 1.0, -1.0], [1.0, -1.0, 1.0]]
1


In [12]:
#############################################################################
#LQR
#############################################################################

# Define the system
A = np.array([[1., 3.], [-2., 2.]])
print(f'A = {A.tolist()}')

B = np.array([[-1.], [1.]])
print(f'B = {B.tolist()}')

# Define the weights
Q = np.eye(2)
print(f'Q = {Q.tolist()}')

R = np.eye(1)
print(f'R = {R.tolist()}')

# Define the initial condition
x0 = np.array([[1.], [-2.]])

# Find the optimal cost matrix and gain matrix (both should be 2D NumPy arrays)
P = linalg.solve_continuous_are(A, B, Q, R)
print(f'P = {P.tolist()}')

K = linalg.inv(R) @  B.T @ P
print(f'K = {K.tolist()}')

# Find the corresponding input at the initial time (should be 2D NumPy array)
u = - K @ x0
print(f'u = {u.tolist()}')

# Find the corresponding total cost over all time (should be a scalar - a single floating-point number)
total_cost = (x0.T @ P @ x0).item()
print(f'total_cost = {total_cost}')

A = [[1.0, 3.0], [-2.0, 2.0]]
B = [[-1.0], [1.0]]
Q = [[1.0, 0.0], [0.0, 1.0]]
R = [[1.0]]
P = [[1.8674319231246386, 0.9922146371413154], [0.9922146371413154, 6.855134047563073]]
K = [[-0.8752172859833232, 5.862919410421758]]
u = [[12.601056106826839]]
total_cost = 25.31910956481167


In [4]:
import numpy as np
from scipy import linalg

A = np.array([[0.40, -0.30, 0.80], [-0.60, -0.90, 1.00], [0.80, -1.00, -1.00]])
B = np.array([[0.50, 0.90], [-0.30, -0.70], [-1.00, -1.00]])
Q = np.array([[2.60, 0.00, -0.55], [0.00, 3.60, 0.00], [-0.55, 0.00, 2.60]])
R = np.array([[2.30, 0.15], [0.15, 2.20]])
t0 = 0.90
x0 = np.array([[-0.75], [-0.13], [-0.90]])

P = linalg.solve_continuous_are(A, B, Q, R)
print(f'P = {P.tolist()}')

K = linalg.inv(R) @  B.T @ P
print(f'K = {K.tolist()}')

P = [[10.696598582024512, -2.5741200728296336, 4.608838858965351], [-2.5741200728296336, 2.1278393768936925, -1.0987728066354243], [4.608838858965351, -1.0987728066354243, 2.997418326162795]]
K = [[0.45711853323972873, -0.2803955277129482, -0.21585293539444272], [3.0688255162961333, -1.2115288607181312, 0.8872979781181747]]


In [2]:
1+1

2

In [14]:
import numpy as np

A = np.array([[-0.50, 0.40], [-0.70, 0.90]])
B = np.array([[-0.90, -0.90], [0.40, 0.70]])
Q = np.array([[1.70, 0.35], [0.35, 1.60]])
R = np.array([[2.50, -0.10], [-0.10, 2.70]])
t0 = 0.90
x0 = np.array([[-0.30], [0.74]])

P = linalg.solve_continuous_are(A, B, Q, R)
print(f'P = {P.tolist()}')

K = linalg.inv(R) @  B.T @ P
print(f'K = {K.tolist()}')

# Find the corresponding input at the initial time (should be 2D NumPy array)
u = - K @ x0
print(f'u = {u.tolist()}')

P = [[1.100429553506857, -0.4389057757472721], [-0.4389057757472721, 6.415639834764476]]
K = [[-0.4863240529594425, 1.2587579176353523], [-0.4986122394352614, 1.8562366201004492]]
u = [[-1.0773780749379933], [-1.5231987707049108]]


In [15]:
import numpy as np

A = np.array([[1.00, -0.40, -0.10, -0.80], [0.40, 0.20, 0.20, 1.00], [0.60, 0.90, 0.90, -1.00], [0.50, -1.00, 0.60, -0.50]])
B = np.array([[0.60, -0.60, 0.20], [0.70, -1.00, -0.30], [1.00, -1.00, 0.10], [0.10, 0.50, -0.30]])
Q = np.array([[4.90, -0.10, 0.20, 0.05], [-0.10, 3.50, 0.45, -0.35], [0.20, 0.45, 4.70, -0.15], [0.05, -0.35, -0.15, 4.70]])
R = np.array([[2.10, 0.45, 0.00], [0.45, 2.20, -0.45], [0.00, -0.45, 2.20]])
t0 = 0.00
x0 = np.array([[0.43], [-0.61], [-0.14], [-0.78]])

P = linalg.solve_continuous_are(A, B, Q, R)
print(f'P = {P.tolist()}')

K = linalg.inv(R) @  B.T @ P
print(f'K = {K.tolist()}')

# Find the corresponding input at the initial time (should be 2D NumPy array)
u = - K @ x0
print(f'u = {u.tolist()}')

# Find the corresponding total cost over all time (should be a scalar - a single floating-point number)
total_cost = (x0.T @ P @ x0).item()
print(f'total_cost = {total_cost}')

P = [[19.927804002957647, -6.54655511817392, -8.429270464715637, -5.475355292035919], [-6.54655511817392, 4.856137704088229, 1.8688271322899692, 2.2557304588215095], [-8.429270464715637, 1.8688271322899692, 8.105751399199958, 2.7170762323143736], [-5.475355292035919, 2.2557304588215095, 2.7170762323143736, 6.141115011373602]]
K = [[-0.9768318923216781, 1.030106886859504, 2.7376248566621864, 0.7364029939799843], [0.9969662200203131, -1.3276910272787343, -2.490969917301337, 0.17453242677171343], [3.271746216450935, -1.751568055251881, -1.5327211023591072, -1.4835806746304585]]
u = [[2.006064729919713], [-1.4511874967890133], [-3.847081267319582]]
total_cost = 20.567980436972746


In [3]:
import numpy as np
import sympy as sym

e_lat, e_head, v, w, theta, theta_dot,tau_left, tau_right = sym.symbols('e_lat, e_head, v, w, theta, theta_dot,tau_left, tau_right')

e_dot_lat = v*sym.sin(e_head)
edot_head = w
n_h = 2400*tau_left + 2400*tau_right + 2808*(theta_dot**2 +w**2)*sym.sin(theta)+13*(250*tau_left + 250*tau_right - 195*w**2*sym.sin(2*theta)-8829*sym.sin(theta))*sym.cos(theta)
d_h = 11700*sym.cos(theta)**2 - 12168
v_dot = -n_h/d_h
n_w = 32*(-875*tau_left + 875*tau_right - 1443*theta_dot*w*sym.sin(2*theta) - 2925*v*w*sym.sin(theta))
d_w = 13*(3120*sym.sin(theta)**2 + 2051)
w_dot = n_w/d_w
n_t = 42250*tau_left + 42250*tau_right - 32955*w**2*sym.sin(2*theta) + 300*(100*tau_left + 100*tau_right + 117*(theta_dot**2 + w**2)*sym.sin(theta))*sym.cos(theta) - 1492101*sym.sin(theta)
d_t = 1404*(25*sym.cos(theta)**2 - 26) 
theta_ddot = n_t/d_t

f = sym.Matrix([[e_dot_lat],[edot_head],[v_dot],[w_dot], [theta_ddot]])

In [4]:
f

Matrix([
[                                                                                                                                                                                                 v*sin(e_head)],
[                                                                                                                                                                                                             w],
[       (-2400*tau_left - 2400*tau_right - (2808*theta_dot**2 + 2808*w**2)*sin(theta) - (3250*tau_left + 3250*tau_right - 2535*w**2*sin(2*theta) - 114777*sin(theta))*cos(theta))/(11700*cos(theta)**2 - 12168)],
[                                                                                     (-28000*tau_left + 28000*tau_right - 46176*theta_dot*w*sin(2*theta) - 93600*v*w*sin(theta))/(40560*sin(theta)**2 + 26663)],
[(42250*tau_left + 42250*tau_right - 32955*w**2*sin(2*theta) + (30000*tau_left + 30000*tau_right + 300*(117*theta_dot**2 + 117*w**2)*sin(theta))*cos(th

In [10]:
e_le = 0
e_he = 0
ve = 0
we = 0
thetae = 0
thetadote = 0
tau_Le = 0
tau_Re = 0



#Create lambda functions A
A_num = sym.lambdify((e_lat, e_head, v, w, theta, theta_dot), f.jacobian([e_lat, e_head, v, w, theta_dot]))

A = A_num(e_le,e_he, ve, we, thetae, thetadote)

print(A)

# Create lambda functions B
B_num = sym.lambdify((e_lat, e_head, v, w, theta, theta_dot), f.jacobian([tau_left, tau_right])) 

# Evaluate lambda function at equilibrium point
B = B_num(e_le, e_he, ve, we, thetae, thetadote)

# Display the result
print(B)



[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -0. -0.]]
[[  0.           0.        ]
 [  0.           0.        ]
 [ 12.07264957  12.07264957]
 [ -1.05014439   1.05014439]
 [-51.46011396 -51.46011396]]


In [5]:
import numpy as np
Z = np.array([[0.0, 0.0, 0.0, 0.0, -1.05014439485429, 1.05014439485429, 0, 0, 0, 0, 0, 0], [0.0, 0.0, -1.0501443948542923, 1.0501443948542923, 0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, -51.460113960113965, -51.460113960113965, 0, 0, -54689.2361111111, -54689.2361111111, 0, 0, -58120985.6770833, -58120985.6770833], [12.072649572649572, 12.072649572649572, 0, 0, 12620.5929487179, 12620.5929487179, 0, 0, 13412535.1562500, 13412535.1562500, 0, 0], [-1.0501443948542923, 1.0501443948542923, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [-51.460113960113965, -51.460113960113965, 0, 0, -54689.2361111111, -54689.2361111111, 0, 0, -58120985.6770833, -58120985.6770833, 0, 0]])
print(Z)
print(np.linalg.matrix_rank(Z))

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -1.05014439e+00  1.05014439e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.05014439e+00  1.05014439e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.14601140e+01 -5.14601140e+01
   0.00000000e+00  0.00000000e+00 -5.46892361e+04 -5.46892361e+04
   0.00000000e+00  0.00000000e+00 -5.81209857e+07 -5.81209857e+07]
 [ 1.20726496e+01  1.20726496e+01  0.00000000e+00  0.00000000e+00
   1.26205929e+04  1.26205929e+04  0.00000000e+00  0.00000000e+00
   1.34125352e+07  1.34125352e+07  0.00000000e+00  0.00000000e+00]
 [-1.05014439e+00  1.05014439e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.

In [ ]:
class RobotController:
    """
    A 'class' allows functions to share a set of variables without
    having to make those variables 'global'.
    
    Our control design has a bunch of variables (the time step, the
    equilibrium point, the state-space model, the controller and observer
    gains, and the state estimate) that need to be shared among several
    different functions (to initialize everything, to reset the state
    estimate, and to run the controller and observer), so the use of a
    class is helpful.
        
    You can read more about classes here:
    
        https://docs.python.org/3/tutorial/classes.html
    
    We name this particular class 'RobotController'. Everything inside
    it must be indented.
    """
    
    def __init__(self):
        """
        This function is called once each time we create an instance of
        the class as:
        
            controller = RobotController()
        
        It is the right place to define variables that will be used by
        all the other functions.
        """
        
        # Choose time step
        self.dt = 0.01 # <--- (1)
        
        # Define equilibrium point
        self.q_e = 2. # <--- (2)
        self.v_e = 0. # <--- (3)
        self.tau_e = 1. # <--- (4)
        
        # Define state-space model
        self.A = np.array([[0.,1.],
                          [0.,0.]]) # <--- (5)
        self.B = np.array([[0.],
                          [1.]]) # <--- (6)
        self.C = np.array([[1.,0.]]) # <--- (7)
        
        # Define controller and observer gains
        self.K = np.array([[5.,1.]]) # <--- (8)
        self.L = np.array([[10.],
                          [10.]]) # <--- (9)
        
        # Run the reset function to initialize the state estimate
        self.reset()
        
    
    def reset(self):
        """
        This function can be called from another function in the class as:
        
            self.reset()
        
        Or, it can be called using an instance 'controller' of the class as:
        
            controller.reset()
        
        It initializes the state estimate. This allows us to 'restart' the
        observer without creating a whole new instance of the class.
        """
        
        # Initialize the state estimate
        self.xhat = np.array([[0.],
                             [0.]]) # <--- (10)
        
    
    def run(self, q):
        """
        This function can be called from another function in the class as:
        
            self.run(q)
        
        Or, it can be called using an instance 'controller' of the class as:
        
            controller.run(q)
        
        It applies the controller to choose (and return) a torque, and applies
        the observer to update the state estimate with the sensor measurement.
        
        Note that we apply the controller BEFORE we apply the observer. This is
        a choice - we could have applied the controller after the observer. Feel
        free to play around with this choice in your own design projects. But,
        for homework problems, please do as we suggest here.
        
        (It is a little bit simpler in any case - if we wanted to apply the
        observer first, then we would have to keep track of the input that had
        been chosen at the previous time step.)
        """
        
        # Apply controller
        u = -self.K@self.xhat # <--- (11) Don't forget to use the state estimate and not the state!
        
        # Convert input to actuator commands
        tau = u[0.,0.] + self.tau_e # <--- (12) Don't forget to extract the torque and add the equilibrium value!
        
        # Define output
        y = np.array([[q-self.q_e]]) #self.C@self.xhat # <--- (13) Don't forget that this is defined using the sensor measurement q
                        #           and not the state estimate!
        
        # Apply observer to update state estimate
        self.xhat += self.dt*(self.A@self.xhat + self.B@u - L@(C@self.xhat - y)) #0. # <--- (14) Note the syntax: "+=" means that we are adding something to
                        #           self.xhat - this is equivalent to saying:
                        #
                        #               self.xhat = self.xhat + 0.
        
        return float(tau)

In [ ]:
class RobotController:
    """
    A 'class' allows functions to share a set of variables without
    having to make those variables 'global'.
    
    Our control design has a bunch of variables (the time step, the
    equilibrium point, the state-space model, the controller and observer
    gains, and the state estimate) that need to be shared among several
    different functions (to initialize everything, to reset the state
    estimate, and to run the controller and observer), so the use of a
    class is helpful.
        
    You can read more about classes here:
    
        https://docs.python.org/3/tutorial/classes.html
    
    We name this particular class 'RobotController'. Everything inside
    it must be indented.
    """
    
    def __init__(self):
        """
        This function is called once each time we create an instance of
        the class as:
        
            controller = RobotController()
        
        It is the right place to define variables that will be used by
        all the other functions.
        """
        
        # Choose time step
        self.dt = 0.01 # <--- (1)
        
        # Define equilibrium point
        self.q_e = 2. # <--- (2)
        self.v_e = 0. # <--- (3)
        self.tau_e = 1. # <--- (4)
        
        # Define state-space model
        self.A = np.array([[0.,1.],
                          [0.,0.]]) # <--- (5)
        self.B = np.array([[0.],
                          [1.]]) # <--- (6)
        self.C = np.array([[1.,0.]]) # <--- (7)
        
        # Define controller and observer gains
        self.K = np.array([[5.,1.]]) # <--- (8)
        self.L = np.array([[10.],
                          [10.]]) # <--- (9)
        
        # Run the reset function to initialize the state estimate
        self.reset()
        
    
    def reset(self):
        """
        This function can be called from another function in the class as:
        
            self.reset()
        
        Or, it can be called using an instance 'controller' of the class as:
        
            controller.reset()
        
        It initializes the state estimate. This allows us to 'restart' the
        observer without creating a whole new instance of the class.
        """
        
        # Initialize the state estimate
        self.xhat = np.array([[0.],
                             [0.]]) # <--- (10)
        
    
    def run(self, q):
        """
        This function can be called from another function in the class as:
        
            self.run(q)
        
        Or, it can be called using an instance 'controller' of the class as:
        
            controller.run(q)
        
        It applies the controller to choose (and return) a torque, and applies
        the observer to update the state estimate with the sensor measurement.
        
        Note that we apply the controller BEFORE we apply the observer. This is
        a choice - we could have applied the controller after the observer. Feel
        free to play around with this choice in your own design projects. But,
        for homework problems, please do as we suggest here.
        
        (It is a little bit simpler in any case - if we wanted to apply the
        observer first, then we would have to keep track of the input that had
        been chosen at the previous time step.)
        """
        
        # Apply controller
        u = -self.K@self.xhat # <--- (11) Don't forget to use the state estimate and not the state!
        
        # Convert input to actuator commands
        tau = u[0,0] + self.tau_e # <--- (12) Don't forget to extract the torque and add the equilibrium value!
        
        # Define output
        y = np.array([[q-self.q_e]]) #self.C@self.xhat # <--- (13) Don't forget that this is defined using the sensor measurement q
                        #           and not the state estimate!
        
        # Apply observer to update state estimate
        self.xhat += self.dt*(self.A@self.xhat + self.B@u - self.L@(self.C@self.xhat - y)) #0. # <--- (14) Note the syntax: "+=" means that we are adding something to
                        #           self.xhat - this is equivalent to saying:
                        #
                        #               self.xhat = self.xhat + 0.
        
        return float(tau)