In [6]:
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla

#Problem 1

#OMEGA = Captital omega 
#w = lowercase omega
#i = i

#Orbit
muE = 398600
rvec = np.array([-6115.75, -6586.18, -58.65]) 
vvec = np.array([4.42, -4.26, -1.08]) 

print("r =", rvec)
print("v =",vvec)
print(       )

hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = np.cross(kvec,hvec) #n cross k func
nmag = np.linalg.norm(nvec)
print("nmag =", nmag)
print("Normal Vec =", nvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

print("rmag =",rmag)
print("vmag =", vmag)

evec = 1/muE * ((vmag**2 - muE/rmag)*rvec - (rvec@vvec)*vvec)
emag = np.linalg.norm(evec)

print("eccentricity vec =", evec)
print("eccentricity mag =", emag)
print(      )

P = (np.linalg.norm(hvec)**2)/muE
a = P/(1-emag**2)

print("a =",a)
print(    )

## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
print("hmag =", hmag)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i * 180/m.pi)

I = [1,0,0] #i direction

if nvec[1]>0:
    OMEGA = m.acos(nvec[0]/nmag) 
else:
    OMEGA = 2*m.pi - m.acos(nvec[0]/nmag)

print("OMEGA angle rad =", OMEGA )

ndot = np.dot(nvec,evec)
emag = np.linalg.norm(evec)

if evec[2]>0:
    w = m.acos(ndot/(nmag*emag))
else: 
    w = 2*m.pi - m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) rad =", w)

e_f = evec@rvec
if np.dot(rvec,vvec) > 0:
    f = m.acos(e_f/(emag*np.linalg.norm(rvec)))
else:
    f = 2*m.pi - m.acos(e_f/(emag*np.linalg.norm(rvec)))
print("True anomaly at epoch (f) rad =",f )



r = [-6115.75 -6586.18   -58.65]
v = [ 4.42 -4.26 -1.08]

angular vel vec= [ 6863.2254 -6864.243  55164.0106]
hmag = 56011.514533452544
nmag = 9706.786020833784
Normal Vec = [6864.243  6863.2254   -0.    ]
rmag = 8987.970008706083
vmag = 6.233008904213117
eccentricity vec = [0.07227857 0.10247818 0.00375917]
eccentricity mag = 0.1254595601171984

a = 7996.640026667112

angle of inclination (i) = 9.97973396000402
OMEGA angle rad = 0.7853240346529133
argument of periapsis (w) rad = 0.1737713830106454
True anomaly at epoch (f) rad = 3.0054839262199513


In [7]:
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla

#Problem 1

#OMEGA = Captital omega 
#w = lowercase omega
#i = i

#Orbit
muE = 398600
rvec = np.array([6590, 0, 0]) 
vvec = np.array([0, 10.153, 1.247]) 

print("r =", rvec)
print("v =",vvec)
print(       )

hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = np.cross(kvec,hvec) #n cross k func
nmag = np.linalg.norm(nvec)
print("nmag =", nmag)
print("Normal Vec =", nvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

print("rmag =",rmag)
print("vmag =", vmag)

evec = 1/muE * ((vmag**2 - muE/rmag)*rvec - (rvec@vvec)*vvec)
emag = np.linalg.norm(evec)

print("eccentricity vec =", evec)
print("eccentricity mag =", emag)
print(      )

P = (np.linalg.norm(hvec)**2)/muE
a = P/(1-emag**2)

print("a =",a)
print(    )

## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
print("hmag =", hmag)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i * 180/m.pi)

I = [1,0,0] #i direction

if nvec[1]>0:
    OMEGA = m.acos(nvec[0]/nmag) 
else:
    OMEGA = 2*m.pi - m.acos(nvec[0]/nmag)

print("OMEGA angle rad =", OMEGA )

ndot = np.dot(nvec,evec)
emag = np.linalg.norm(evec)

if evec[2]>0:
    w = m.acos(ndot/(nmag*emag))
else: 
    w = 2*m.pi - m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) rad =", w)

e_f = evec@rvec
if np.dot(rvec,vvec) > 0:
    f = m.acos(e_f/(emag*np.linalg.norm(rvec)))
else:
    f = 2*m.pi - m.acos(e_f/(emag*np.linalg.norm(rvec)))
print("True anomaly at epoch (f) rad =",f )



r = [6590    0    0]
v = [ 0.    10.153  1.247]

angular vel vec= [    0.   -8217.73 66908.27]
hmag = 56011.514533452544
nmag = 8217.730000000001
Normal Vec = [8217.73    0.     -0.  ]
rmag = 6590.0
vmag = 10.229292155374193
eccentricity vec = [0.72997284 0.         0.        ]
eccentricity mag = 0.7299728414952333

a = 24404.952585107

angle of inclination (i) = 7.002047821749462
OMEGA angle rad = 6.283185307179586
argument of periapsis (w) rad = 6.283185307179586
True anomaly at epoch (f) rad = 6.283185307179586


In [35]:
#####Classical Orbital Elements (COE) to r,v#####
# Problem 2a
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla

a_1 = 8000
e_1 = 0.125
i_1 = 10 #deg
OMEGA_1 = 45 #deg
w_1 = 10 #deg
M_1 = 170 #deg
muE = 398600

#when testing use OMEGA = 0, w = 0, i = 0 to get identity matrix
RotMatrix = np.array([[m.cos(OMEGA_1)*m.cos(w_1) - m.sin(OMEGA_1)*m.sin(w_1)*m.cos(i_1) , -m.cos(OMEGA_1)*m.sin(w_1) - m.sin(OMEGA_1)*m.cos(w_1)*m.cos(i_1), m.sin(OMEGA_1)*m.sin(i_1)],
    [m.sin(OMEGA_1)*m.cos(w_1) + m.cos(OMEGA_1)*m.sin(w_1)*m.cos(i_1), -m.sin(OMEGA_1)*m.sin(w_1) + m.cos(OMEGA_1)*m.cos(w_1)*m.cos(i_1), -m.cos(OMEGA_1)*m.sin(i_1)],
    [m.sin(w_1)*m.sin(i_1), m.cos(w_1)*m.sin(i_1), m.cos(i_1)]])

print("Rotation Matrix =", RotMatrix)

#M = E1 - e*sin(E1)
E_in  = M_1
    
err = 1
while abs(err) > 1e-10:
    err = E_in-e_1*np.sin(E_in)-M_1
    dgdE = 1 - e_1*np.cos(E_in)
    E1 = E_in - err/dgdE
    E_in = E1
    print("E =", E_in * m.pi/180)

f_1 = 2*m.atan((m.tan(E_in/2))/(m.sqrt((1-e)/(1+e))))
print("True anomaly at epoch (f) rad =",f_1)

def rpqw(a,e,f):
    P = a*(1-(e**2))
    r1 = P/(1+e*m.cos(f))
    rpqw = np.array([r1*m.cos(f), r1*m.sin(f),0])
    return rpqw

def vpqw(a,e,f):
    P = a*(1-(e**2))
    vpqw = np.array([m.sqrt(muE/P)*-m.sin(f), m.sqrt(muE/P)*(e+m.cos(f)), 0])
    return vpqw

print(    )
# print("rpqw =", rpqw(a_1,e_1,f_1))
# print("vpqw =", vpqw(a_1,e_1,f_1))

rvec = RotMatrix@rpqw(a_1,e_1,f_1)
vvec = RotMatrix@vpqw(a_1,e_1,f_1)

print(      )
print("rvec =", rvec)
print("vvec =", vvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

print("rmag =",rmag)
print("vmag =", vmag)

####
hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = np.cross(kvec,hvec) #n cross k func
nmag = np.linalg.norm(nvec)
print("nmag =", nmag)
print("Normal Vec =", nvec)


evec = 1/muE * ((vmag**2 - muE/rmag)*rvec - (rvec@vvec)*vvec)
emag = np.linalg.norm(evec)

print("eccentricity vec =", evec)
print("eccentricity mag =", emag)
print(      )


## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
print("hmag =", hmag)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i * 180/m.pi)

I = [1,0,0] #i direction

ndot = np.dot(nvec,evec)
emag = np.linalg.norm(evec)

if evec[2]>0:
    w = m.acos(ndot/(nmag*emag))
else: 
    w = 2*m.pi - m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) rad =", w)

theta = w + f_1
print("theta =", theta)

Rotation Matrix = [[-0.82919689 -0.31328474 -0.46290948]
 [-0.47417381  0.83275772  0.28578625]
 [ 0.29595897  0.45647263 -0.83907153]]
E = 2.967916450261317
E = 2.9679153754069807
E = 2.967915375405146
True anomaly at epoch (f) rad = 0.45524259291555486


rvec = [-6248.14868049  -422.92532661  3303.00924403]
vvec = [0.3133418  7.54508428 2.39697379]
rmag = 7080.119902344115
vmag = 7.922875941630364
angular vel vec= [-25935.22403617  16011.61950595 -47010.28818238]
nmag = 30479.629345017536
Normal Vec = [-16011.61950595 -25935.22403617      0.        ]
eccentricity vec = [-0.10364961 -0.05927173  0.03699487]
eccentricity mag = 0.12500000000000008

hmag = 56026.55620328632
angle of inclination (i) = 32.957795130823214
argument of periapsis (w) rad = 0.5752220392306211
theta = 1.030464632146176


In [37]:
#####Classical Orbital Elements (COE) to r,v#####
# Problem 2b
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla

rp_2 = 6611
e_2 = 0.01
i_2 = 90 #deg
OMEGA_2 = 0 #deg
w_2 = 0 #deg
M_2 = 355 #deg
muE = 398600

#when testing use OMEGA = 0, w = 0, i = 0 to get identity matrix
RotMatrix = np.array([[m.cos(OMEGA_2)*m.cos(w_2) - m.sin(OMEGA_2)*m.sin(w_2)*m.cos(i_2) , -m.cos(OMEGA_2)*m.sin(w_2) - m.sin(OMEGA_2)*m.cos(w_2)*m.cos(i_2), m.sin(OMEGA_2)*m.sin(i_2)],
    [m.sin(OMEGA_2)*m.cos(w_2) + m.cos(OMEGA_2)*m.sin(w_2)*m.cos(i_2), -m.sin(OMEGA_2)*m.sin(w_2) + m.cos(OMEGA_2)*m.cos(w_2)*m.cos(i_2), -m.cos(OMEGA_2)*m.sin(i_2)],
    [m.sin(w_2)*m.sin(i_2), m.cos(w_2)*m.sin(i_2), m.cos(i_2)]])

print("Rotation Matrix =", RotMatrix)

#M = E1 - e*sin(E1)
E_in  = M_2
    
err = 1
while abs(err) > 1e-10:
    err = E_in-e_2*np.sin(E_in)-M_2
    dgdE = 1 - e_2*np.cos(E_in)
    E1 = E_in - err/dgdE
    E_in = E1
    print("E =", E_in * m.pi/180)

f_2 = 2*m.atan((m.tan(E_in/2))/(m.sqrt((1-e_2)/(1+e_2))))
print("True anomaly at epoch (f) rad =",f_2)

a_2 = rp_2/(1-e_2)

def rpqw(a,e,f):
    P = a*(1-(e**2))
    r1 = P/(1+e*m.cos(f))
    rpqw = np.array([r1*m.cos(f), r1*m.sin(f),0])
    return rpqw

def vpqw(a,e,f):
    P = a*(1-(e**2))
    vpqw = np.array([m.sqrt(muE/P)*-m.sin(f), m.sqrt(muE/P)*(e+m.cos(f)), 0])
    return vpqw

print(    )
# print("rpqw =", rpqw(a_1,e_1,f_1))
# print("vpqw =", vpqw(a_1,e_1,f_1))

rvec = RotMatrix@rpqw(a_2,e_2,f_2)
vvec = RotMatrix@vpqw(a_2,e_2,f_2)

print(      )
print("rvec =", rvec)
print("vvec =", vvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

print("rmag =",rmag)
print("vmag =", vmag)

####
hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = np.cross(kvec,hvec) #n cross k func
nmag = np.linalg.norm(nvec)
print("nmag =", nmag)
print("Normal Vec =", nvec)


evec = 1/muE * ((vmag**2 - muE/rmag)*rvec - (rvec@vvec)*vvec)
emag = np.linalg.norm(evec)

print("eccentricity vec =", evec)
print("eccentricity mag =", emag)
print(      )


## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
print("hmag =", hmag)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i * 180/m.pi)

I = [1,0,0] #i direction

ndot = np.dot(nvec,evec)
emag = np.linalg.norm(evec)

if evec[2]>0:
    w = m.acos(ndot/(nmag*emag))
else: 
    w = 2*m.pi - m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) rad =", w)

theta = w + f_2
print("theta =", theta)

Rotation Matrix = [[ 1.          0.          0.        ]
 [ 0.         -0.44807362 -0.89399666]
 [ 0.          0.89399666 -0.44807362]]
E = 6.195918839370778
E = 6.195918839370779
True anomaly at epoch (f) rad = -3.1415631046768198


rvec = [-6.74455555e+03  8.92985110e-02 -1.78168426e-01]
vvec = [ 2.28305246e-04  3.42735388e+00 -6.83825787e+00]
rmag = 6744.555555525814
vmag = 7.649086572623557
angular vel vec= [     0.         -46121.01014444 -23115.9786567 ]
nmag = 46121.010144436215
Normal Vec = [46121.01014444     0.            -0.        ]
eccentricity vec = [ 1.0000000e-02 -5.2224490e-22  1.0444898e-21]
eccentricity mag = 0.010000000000000196

hmag = 51589.68933808382
angle of inclination (i) = 63.37984382259113
argument of periapsis (w) rad = 0.0
theta = -3.1415631046768198


In [ ]:
# Problem 3
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla

Msun = 1.989*10**30
Mear = 5.972*1**24
Mmoon = 7.347*10**22
Mjup = 1.898*10**27
Meur = 4.799*10**22
Mapop = 2.699*10**10

dsun_a = 149*10**6
dsun_j = 750*10**6
dear_m = 384*10**3
dj_eur = 670*10**3

#Problem 3a 
## Sun Jupiter system
L1 = x  - (1-mu)/(mu+x)**2 + mu/(x-1+mu)**2 = 0
L2 = x  - (1-mu)/(mu+x)**2 - mu/(x-1+mu)**2 = 0
L3 = x  + (1-mu)/(mu+x)**2 + mu/(x-1+mu)**2 = 0
L4 = (1/2 - mu, m.sqrt(3)/2)
L5 = (1/2 - mu, -m.sqrt(3)/2)

#Problem 3b
## Jupiter Europa system
L1 = x  - (1-mu)/(mu+x)**2 + mu/(x-1+mu)**2 = 0
L2 = x  - (1-mu)/(mu+x)**2 - mu/(x-1+mu)**2 = 0

#Problem 3c
## Sun Apophis system
L1 = x  - (1-mu)/(mu+x)**2 + mu/(x-1+mu)**2 = 0


In [ ]:
# Problem 4
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla

#case 1
mu_1 = 0.012150585609262
r0_1 = [1.118824382902157, 0.0, 0.014654873101278] #Distance Units
v0_1 = [0.0, 0.180568501159703, 0.0] #Velocity Units
t_1 = 3.41213481127321 #Time Units

#case 2
mu_2 = 0.012150585609262
r0_2 = [0.7, 0.0, 0.01] #Distance Units
v0_2 = [ 0.0, 0.8, 0.0] #Velocity Units
t_2 = 30 #Time Units

#case 3
mu_3 = 0.012150585609262
r0_3 = [1 - mu, 0.5, 0.0] #Distance Units
v0_3 = [-1.0*10**-15, 0.0, 0.0] #Velocity Units
t_3 = 30 #Time Units

xddot - 2*ydot = dU/dx
yddot +2*xdot = dU/dz
zddot = dU/dz

U = 1/2 * (x**2 + y**2) + (1-mu)/r1 + mu/r2

r1 = m.sqrt((x-x1)**2 + y**2 +z**2)
r2 = m.sqrt((x-x2)**2 + y**2 +z**2)