In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla

#Problem 1a

#OMEGA = Captital omega 
#w = lowercase omega
#i = i

#Orbit 1
a = 7371.0 #km
e = 0.1 
i = 28.5 * (m.pi/180) #deg to rad
w = 191 * (m.pi/180) #deg to rad
OMEGA = 273 * (m.pi/180) #deg to rad
f = 10 * (m.pi/180) #deg to rad
r = np.array([-2413.9, 6083.8, -1136.0]) #km
v = np.array([-6.5461, -3.1365, -3.6385]) #km/s

print("r =", r)
print("v =",v)
print(       )
#####Classical Orbital Elements (COE) to r,v#####

#when testing use OMEGA = 0, w = 0, i = 0 to get identity matrix
RotMatrix = np.array([[m.cos(OMEGA)*m.cos(w) - m.sin(OMEGA)*m.sin(w)*m.cos(i) , -m.cos(OMEGA)*m.sin(w) - m.sin(OMEGA)*m.cos(w)*m.cos(i), m.sin(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.cos(w) + m.cos(OMEGA)*m.sin(w)*m.cos(i), -m.sin(OMEGA)*m.sin(w) + m.cos(OMEGA)*m.cos(w)*m.cos(i), -m.cos(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.sin(i), m.cos(OMEGA)*m.sin(i), m.cos(i)]])

print("Rotation Matrix =", RotMatrix)

muE = 3.986*10**5 #km^3/s^2

def rpqw(a,e,f):
    P = a*(1-(e**2))
    r1 = P/(1+e*m.cos(f))
    rpqw = np.array([r1*m.cos(f), r1*m.sin(f),0])
    return rpqw

def vpqw(a,e,f):
    P = a*(1-(e**2))
    vpqw = np.array([m.sqrt(muE/P)*-m.sin(f), m.sqrt(muE/P)*(e+m.cos(f)), 0])
    return vpqw

print(    )
print("rpqw =", rpqw(7371.0,0.1,10 * (m.pi/180)))
print("vpqw =", vpqw(7371.0,0.1,10 * (m.pi/180)))

rvec = RotMatrix@rpqw(7371.0,0.1,10 * (m.pi/180))
vvec = RotMatrix@vpqw(7371.0,0.1,10 * (m.pi/180))

print(      )
print("rvec =", rvec)
print("vvec =", vvec)

#####r,v to COE#####
print(2*2)

In [23]:
##
#Orbit 2
a = 17248.3 #km
e = 0.5965
i = 6.0126 * (m.pi/180) #deg to rad
w = 354.68 * (m.pi/180) #deg to rad
OMEGA = 0 * (m.pi/180) #deg to rad
f = 5.3247 * (m.pi/180) #deg to rad
r = np.array([6971, 0, 0]) #km
v = np.array([0.3315, 9.4942, 1]) #km/s

#Classical Orbital Elements (COE) to r,v
#when testing use OMEGA = 0, w = 0, i = 0 to get identity matrix
RotMatrix = np.array([[m.cos(OMEGA)*m.cos(w) - m.sin(OMEGA)*m.sin(w)*m.cos(i) , -m.cos(OMEGA)*m.sin(w) - m.sin(OMEGA)*m.cos(w)*m.cos(i), m.sin(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.cos(w) + m.cos(OMEGA)*m.sin(w)*m.cos(i), -m.sin(OMEGA)*m.sin(w) + m.cos(OMEGA)*m.cos(w)*m.cos(i), -m.cos(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.sin(i), m.cos(OMEGA)*m.sin(i), m.cos(i)]])

print("Rotation Matrix =", RotMatrix)

rvec = RotMatrix@r
vvec = RotMatrix@v

print(   )
print("radius vector =", rvec)
print("velocity vector =", vvec)
print(      )

#r,v to C.O.E
hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = kvec@hvec #results in just z component, must reput into matrix form
n_matrix_vec = np.array([0,0,nvec]) #nvec in matrix form
print("Normal Vec =", nvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

evec = [((1/muE)*((vmag**2)-(muE/rmag))), (1/muE)*(-rmag*vmag),0] # z = 0 bcuz no z comp

print("eccentricity vec =", evec)
print(      )

## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i)

I = [[1,0,0],[0,1,0],[0,0,1]] #identity matrix

n_I = np.linalg.norm(n_matrix_vec@I) #cannot use nvec bcuz nvec is not in matrix form, n_matrix_vec is
nmag = np.linalg.norm(nvec)
OMEGA = m.acos(n_I/nmag)
print("OMEGA angle =", OMEGA)

ndot = n_matrix_vec@evec
emag = np.linalg.norm(evec)
w = m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) =", w)



Rotation Matrix = [[-0.9492449  -0.31453795 -0.        ]
 [ 0.30309336 -0.91470626  0.26729549]
 [-0.         -0.26729549  0.96361461]]

radius vector = [-6617.1861983   2112.86381951     0.        ]
velocity vector = [-3.30096085 -8.31663319 -1.57414226]

angular vel vec= [ -3325.94822391 -10416.39242451  62007.19111651]
Normal Vec = 62007.19111651293
eccentricity vec = [-0.0001439611411186109, -1.0567417679633633e-20, 0]

angle of inclination (i) = 0.17454783680591382
OMEGA angle = 0.0
argument of periapsis (w) = 1.5707963267948966


In [7]:
#1b
a = 6871.0 #km
e = 0.07 
i = 5.2 #deg
w = 37.8 #deg
OMEGA = 89 #deg
f = 213.4 #def

#compute r,v at Earth

#Classical Orbital Elements (COE) to r,v
#when testing use OMEGA = 0, w = 0, i = 0 to get identity matrix
RotMatrix = np.array([[m.cos(OMEGA)*m.cos(w) - m.sin(OMEGA)*m.sin(w)*m.cos(i) , -m.cos(OMEGA)*m.sin(w) - m.sin(OMEGA)*m.cos(w)*m.cos(i), m.sin(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.cos(w) + m.cos(OMEGA)*m.sin(w)*m.cos(i), -m.sin(OMEGA)*m.sin(w) + m.cos(OMEGA)*m.cos(w)*m.cos(i), -m.cos(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.sin(i), m.cos(OMEGA)*m.sin(i), m.cos(i)]])

print("Rotation Matrix =", RotMatrix)
print(          )

muE = 5.972*10**24 #kg
P = a*(1-e**2)

#find rvec
r = P/(1+(e*m.cos(f)))
rline = np.array([(r*m.cos(f)), (r*m.sin(f)), 0])
rvec = RotMatrix@rline

print("radius vector =", rvec)

#find vvec
v = np.array([m.sqrt(muE/P)*(-m.sin(f)), m.sqrt(muE/P)*(e + m.cos(f)), 0])
vvec = RotMatrix@v
print("velocity vector =", vvec)


Rotation Matrix = [[ 0.4669982  -0.45229141 -0.75983232]
 [ 0.87977009  0.15118733  0.45071829]
 [-0.75983232 -0.45071829  0.46851667]]

radius vector = [ 3566.86332092  5266.17764915 -4084.46835751]
velocity vector = [-1.08322519e+10  1.05495787e+10 -1.89896577e+10]


In [2]:
2*2

4

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla
import matplotlib.pyplot as plt

#Problem 1a

#OMEGA = Captital omega 
#w = lowercase omega
#i = i

#Orbit 1
a = 7371.0 #km
e = 0.1 
i = 28.5 #deg
w = 191 #deg
OMEGA = 273 #deg
f = 10 #deg
r = np.array([-2413.9, 6083.8, -1136.0]) #km
v = np.array([-6.5461, -3.1365, -3.6385]) #km/s

#Classical Orbital Elements (COE) to r,v
#when testing use OMEGA = 0, w = 0, i = 0 to get identity matrix
RotMatrix = np.array([[m.cos(OMEGA)*m.cos(w) - m.sin(OMEGA)*m.sin(w)*m.cos(i) , -m.cos(OMEGA)*m.sin(w) - m.sin(OMEGA)*m.cos(w)*m.cos(i), m.sin(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.cos(w) + m.cos(OMEGA)*m.sin(w)*m.cos(i), -m.sin(OMEGA)*m.sin(w) + m.cos(OMEGA)*m.cos(w)*m.cos(i), -m.cos(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.sin(i), m.cos(OMEGA)*m.sin(i), m.cos(i)]])

print("Rotation Matrix =", RotMatrix)

rvec = RotMatrix@r
vvec = RotMatrix@v

print(   )
print("radius vector =", rvec)
print("velocity vector =", vvec)

#r,v to C.O.E
print(      )
hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = kvec@hvec #results in just z component, must reput into matrix form
n_matrix_vec = np.array([0,0,nvec]) #nvec in matrix form
print("Normal Vec =", nvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

evec = [((1/muE)*((vmag**2)-(muE/rmag))), (1/muE)*(-rmag*vmag),0] # z = 0 bcuz no z comp

print("eccentricity vec =", evec)
print(      )

## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i)

I = [[1,0,0],[0,1,0],[0,0,1]] #identity matrix

n_I = np.linalg.norm(n_matrix_vec@I) #cannot use nvec bcuz nvec is not in matrix form, n_matrix_vec is
nmag = np.linalg.norm(nvec)
OMEGA = m.acos(n_I/nmag)
print("OMEGA angle =", OMEGA)

ndot = n_matrix_vec@evec
emag = np.linalg.norm(evec)
w = m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) =", w)


In [4]:
Discuss the trajectory. What is going on here? 

SyntaxError: invalid syntax (<ipython-input-4-af477d26f252>, line 1)

0.9649660284921133