In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np
import math as m
import numpy.linalg as la
import scipy.linalg as sla

#Problem 1a

#OMEGA = Captital omega 
#w = lowercase omega
#i = i

#Orbit 1
a = 7371.0 #km
e = 0.1 
i = 28.5 * (m.pi/180) #deg to rad
w = 191 * (m.pi/180) #deg to rad
OMEGA = 273 * (m.pi/180) #deg to rad
f = 10 * (m.pi/180) #deg to rad
r = np.array([-2413.9, 6083.8, -1136.0]) #km
v = np.array([-6.5461, -3.1365, -3.6385]) #km/s

print("i =", i* 180/m.pi)
print("OMEGA =", OMEGA* 180/m.pi)
print("w =", w* 180/m.pi)
print("f =", f* 180/m.pi)
print("a =",a)
print("e =",e)
print(      )
print("r =", r)
print("v =",v)
print(       )
#####Classical Orbital Elements (COE) to r,v#####

#when testing use OMEGA = 0, w = 0, i = 0 to get identity matrix
RotMatrix = np.array([[m.cos(OMEGA)*m.cos(w) - m.sin(OMEGA)*m.sin(w)*m.cos(i) , -m.cos(OMEGA)*m.sin(w) - m.sin(OMEGA)*m.cos(w)*m.cos(i), m.sin(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.cos(w) + m.cos(OMEGA)*m.sin(w)*m.cos(i), -m.sin(OMEGA)*m.sin(w) + m.cos(OMEGA)*m.cos(w)*m.cos(i), -m.cos(OMEGA)*m.sin(i)],
    [m.sin(w)*m.sin(i), m.cos(w)*m.sin(i), m.cos(i)]])

print("Rotation Matrix =", RotMatrix)

muE = 3.986*10**5 #km^3/s^2

def rpqw(a,e,f):
    P = a*(1-(e**2))
    r1 = P/(1+e*m.cos(f))
    rpqw = np.array([r1*m.cos(f), r1*m.sin(f),0])
    return rpqw

def vpqw(a,e,f):
    P = a*(1-(e**2))
    vpqw = np.array([m.sqrt(muE/P)*-m.sin(f), m.sqrt(muE/P)*(e+m.cos(f)), 0])
    return vpqw

print(    )
print("rpqw =", rpqw(7371.0,0.1,10 * (m.pi/180)))
print("vpqw =", vpqw(7371.0,0.1,10 * (m.pi/180)))

rvec = RotMatrix@rpqw(7371.0,0.1,10 * (m.pi/180))
vvec = RotMatrix@vpqw(7371.0,0.1,10 * (m.pi/180))

print(      )
print("rvec =", rvec)
print("vvec =", vvec)

#####r,v to COE#####
print(      )

hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = np.cross(kvec,hvec) #n cross k func
nmag = np.linalg.norm(nvec)
print("nmag =", nmag)
print("Normal Vec =", nvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

print("rmag =",rmag)
print("vmag =", vmag)

evec = 1/muE * ((vmag**2 - muE/rmag)*rvec - (rvec@vvec)*vvec)
emag = np.linalg.norm(evec)

print("eccentricity vec =", evec)
print("eccentricity mag =", emag)
print(      )

P = (np.linalg.norm(hvec)**2)/muE
a = P/(1-emag**2)

print("a =",a)
print(    )

## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i * 180/m.pi)

I = [1,0,0] #i direction

if nvec[1]>0:
    OMEGA = m.acos(nvec[0]/nmag) 
else:
    OMEGA = 2*m.pi - m.acos(nvec[0]/nmag)

print("OMEGA angle =", OMEGA * 180/m.pi)

ndot = np.dot(nvec,evec)
emag = np.linalg.norm(evec)

if evec[2]>0:
    w = m.acos(ndot/(nmag*emag))
else: 
    w = 2*m.pi - m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) =", w * 180/m.pi)

e_f = evec@rvec
if np.dot(rvec,vvec) > 0:
    f = m.acos(e_f/(emag*np.linalg.norm(rvec)))
else:
    f = 2*m.pi - m.acos(e_f/(emag*np.linalg.norm(rvec)))
print("True anomaly at epoch (f) =",f * 180/m.pi)


i = 28.500000000000004
OMEGA = 273.0
w = 191.0
f = 10.0
a = 7371.0
e = 0.1

r = [-2413.9  6083.8 -1136. ]
v = [-6.5461 -3.1365 -3.6385]

Rotation Matrix = [[-0.2188308  -0.85150234 -0.47650483]
 [ 0.97150588 -0.2356962  -0.02497256]
 [-0.09104618 -0.46839201  0.87881711]]

rpqw = [6542.15160571 1153.55783997    0.        ]
vpqw = [-1.2833883   8.01753057  0.        ]

rvec = [-2413.88146178  6083.84955166 -1135.95521195]
vvec = [-6.54610112 -3.13652075 -3.63849965]

angular vel vec= [-25699.03157122  -1346.82917437  47396.68365483]
nmag = 25734.299534351343
Normal Vec = [  1346.82917437 -25699.03157122      0.        ]
rmag = 6643.0748394289985
vmag = 8.119598635656784
eccentricity vec = [-0.02188308  0.09715059 -0.00910462]
eccentricity mag = 0.09999999999999983

a = 7370.999999999999

angle of inclination (i) = 28.5
OMEGA angle = 273.0
argument of periapsis (w) = 190.99999999999994
True anomaly at epoch (f) = 10.000000000000087


In [20]:
##
#Orbit 2
a = 17248.3 #km
e = 0.5965
i = 6.0126 * (m.pi/180) #deg to rad
w = 354.68 * (m.pi/180) #deg to rad
OMEGA = 0 * (m.pi/180) #deg to rad
f = 5.3247 * (m.pi/180) #deg to rad
r = np.array([6971, 0, 0]) #km
v = np.array([0.3315, 9.4942, 1]) #km/s

print("i =", i* 180/m.pi)
print("OMEGA =", OMEGA* 180/m.pi)
print("w =", w* 180/m.pi)
print("f =", f* 180/m.pi)
print("a =",a)
print("e =",e)
print(      )
print("r =", r)
print("v =",v)
print(       )
#####Classical Orbital Elements (COE) to r,v#####

#when testing use OMEGA = 0, w = 0, i = 0 to get identity matrix
RotMatrix = np.array([[m.cos(OMEGA)*m.cos(w) - m.sin(OMEGA)*m.sin(w)*m.cos(i) , -m.cos(OMEGA)*m.sin(w) - m.sin(OMEGA)*m.cos(w)*m.cos(i), m.sin(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.cos(w) + m.cos(OMEGA)*m.sin(w)*m.cos(i), -m.sin(OMEGA)*m.sin(w) + m.cos(OMEGA)*m.cos(w)*m.cos(i), -m.cos(OMEGA)*m.sin(i)],
    [m.sin(w)*m.sin(i), m.cos(w)*m.sin(i), m.cos(i)]])

print("Rotation Matrix =", RotMatrix)

muE = 3.986*10**5 #km^3/s^2

def rpqw(a,e,f):
    P = a*(1-(e**2))
    r1 = P/(1+e*m.cos(f))
    rpqw = np.array([r1*m.cos(f), r1*m.sin(f),0])
    return rpqw

def vpqw(a,e,f):
    P = a*(1-(e**2))
    vpqw = np.array([m.sqrt(muE/P)*-m.sin(f), m.sqrt(muE/P)*(e+m.cos(f)), 0])
    return vpqw

print(    )
print("rpqw =", rpqw(17248.3,0.5965,5.3247 * (m.pi/180)))
print("vpqw =", vpqw(17248.3,0.5965,5.3247 * (m.pi/180)))

rvec = RotMatrix@rpqw(17248.3,0.5965,5.3247 * (m.pi/180))
vvec = RotMatrix@vpqw(17248.3,0.5965,5.3247 * (m.pi/180))

print(      )
print("rvec =", rvec)
print("vvec =", vvec)

#####r,v to COE#####
hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = np.cross(kvec,hvec) #n cross k func
nmag = np.linalg.norm(nvec)
print("nmag =", nmag)
print("Normal Vec =", nvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

print("rmag =",rmag)
print("vmag =", vmag)

evec = 1/muE * ((vmag**2 - muE/rmag)*rvec - (rvec@vvec)*vvec)
emag = np.linalg.norm(evec)

print("eccentricity vec =", evec)
print("eccentricity mag =", emag)
print(      )

P = (np.linalg.norm(hvec)**2)/muE
a = P/(1-emag**2)

print("a =",a)
print(    )

## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i * 180/m.pi)

I = [1,0,0] #i direction

if nvec[1]>0:
    OMEGA = m.acos(nvec[0]/nmag) 
else:
    OMEGA = 2*m.pi - m.acos(nvec[0]/nmag)

print("OMEGA angle =", OMEGA * 180/m.pi)

ndot = np.dot(nvec,evec)
emag = np.linalg.norm(evec)

if evec[2]>0:
    w = m.acos(ndot/(nmag*emag))
else: 
    w = 2*m.pi - m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) =", w * 180/m.pi)

e_f = evec@rvec
if np.dot(rvec,vvec) > 0:
    f = m.acos(e_f/(emag*np.linalg.norm(rvec)))
else:
    f = 2*m.pi - m.acos(e_f/(emag*np.linalg.norm(rvec)))
print("True anomaly at epoch (f) =",f * 180/m.pi)


i = 6.0126
OMEGA = 0.0
w = 354.68000000000006
f = 5.3247
a = 17248.3
e = 0.5965

r = [6971    0    0]
v = [0.3315 9.4942 1.    ]

Rotation Matrix = [[ 0.99569239  0.09271816  0.        ]
 [-0.0922081   0.99021498 -0.10474717]
 [-0.00971196  0.10429596  0.99449888]]

rpqw = [6940.84717479  646.90096925    0.        ]
vpqw = [-0.55582293  9.53636219  0.        ]

rvec = [6.97092821e+03 5.68682857e-01 5.98974211e-02]
vvec = [0.33076525 9.49430002 1.00000216]
angular vel vec= [-1.76525461e-14 -6.97092347e+03  6.61838957e+04]
nmag = 6970.923468690537
Normal Vec = [ 6.97092347e+03 -1.76525461e-14  0.00000000e+00]
rmag = 6970.928228563672
vmag = 9.552546409239984
eccentricity vec = [ 0.59393051 -0.05500213 -0.00579319]
eccentricity mag = 0.5965000000000013

a = 17248.300000000057

angle of inclination (i) = 6.012600000000035
OMEGA angle = 0.0
argument of periapsis (w) = 354.68000000000006
True anomaly at epoch (f) = 5.324699999999897


In [12]:
#1b
a = 6871.0 #Km
e = 0.07
i = 5.2 * m.pi/180 #deg to rad
w = 37.8 * m.pi/180 #deg to rad
OMEGA = 89 * m.pi/180 #deg to rad
f = 213.4 * m.pi/180 #deg to rad

RotMatrix = np.array([[m.cos(OMEGA)*m.cos(w) - m.sin(OMEGA)*m.sin(w)*m.cos(i) , -m.cos(OMEGA)*m.sin(w) - m.sin(OMEGA)*m.cos(w)*m.cos(i), m.sin(OMEGA)*m.sin(i)],
    [m.sin(OMEGA)*m.cos(w) + m.cos(OMEGA)*m.sin(w)*m.cos(i), -m.sin(OMEGA)*m.sin(w) + m.cos(OMEGA)*m.cos(w)*m.cos(i), -m.cos(OMEGA)*m.sin(i)],
    [m.sin(w)*m.sin(i), m.cos(w)*m.sin(i), m.cos(i)]])

print("Rotation Matrix =", RotMatrix)

muE = 3.986*10**5 #km^3/s^2

def rpqw(a,e,f):
    P = a*(1-(e**2))
    r1 = P/(1+e*m.cos(f))
    rpqw = np.array([r1*m.cos(f), r1*m.sin(f),0])
    return rpqw

def vpqw(a,e,f):
    P = a*(1-(e**2))
    vpqw = np.array([m.sqrt(muE/P)*-m.sin(f), m.sqrt(muE/P)*(e+m.cos(f)), 0])
    return vpqw

print(    )
print("rpqw =", rpqw(6871.0,0.07, 213.4 * m.pi/180))
print("vpqw =", vpqw(6871.0,0.07, 213.4 * m.pi/180))

rvec = RotMatrix@rpqw(6871.0,0.07, 213.4 * m.pi/180)
vvec = RotMatrix@vpqw(6871.0,0.07, 213.4 * m.pi/180)

print(      )
print("rvec =", rvec)
print("vvec =", vvec)


Rotation Matrix = [[-0.5965015  -0.7974799   0.09061878]
 [ 0.80068735 -0.59908035 -0.00158176]
 [ 0.05554935  0.07161379  0.9958844 ]]

rpqw = [-6062.41573148 -3997.42665151     0.        ]
vpqw = [ 4.20307789 -5.83983219  0.        ]

rvec = [ 6804.10750605 -2459.31980212  -623.03410221]
vvec = [ 2.15000653  6.86388002 -0.18473427]


In [19]:
#1c 
rvec = np.array([4589.7,4980.4,2997.5]) #km
vvec = np.array([1.259,4.613,6.208]) #km/s

hvec = np.cross(rvec,vvec) #cross product func
print("angular vel vec=", hvec)

kvec = np.array([0,0,1])
nvec = np.cross(kvec,hvec) #n cross k func
nmag = np.linalg.norm(nvec)
print("nmag =", nmag)
print("Normal Vec =", nvec)

vmag = np.linalg.norm(vvec) #magnitude of vvec
rmag = np.linalg.norm(rvec) #magnitude of rvec

print("rmag =",rmag)
print("vmag =", vmag)

evec = 1/muE * ((vmag**2 - muE/rmag)*rvec - (rvec@vvec)*vvec)
emag = np.linalg.norm(evec)

print("eccentricity vec =", evec)
print("eccentricity mag =", emag)
print(      )

P = (np.linalg.norm(hvec)**2)/muE
a = P/(1-emag**2)

print("a =",a)
print(    )

## take h,n,e vectors and find OMEGA, w, i
h_k = np.linalg.norm(kvec@hvec)
hmag = np.linalg.norm(hvec)
i = m.acos(h_k/hmag)
print("angle of inclination (i) =",i * 180/m.pi)

I = [1,0,0] #i direction

if nvec[1]>0:
    OMEGA = m.acos(nvec[0]/nmag) 
else:
    OMEGA = 2*m.pi - m.acos(nvec[0]/nmag)

print("OMEGA angle =", OMEGA * 180/m.pi)

ndot = np.dot(nvec,evec)
emag = np.linalg.norm(evec)

if evec[2]>0:
    w = m.acos(ndot/(nmag*emag))
else: 
    w = 2*m.pi - m.acos(ndot/(nmag*emag))
print("argument of periapsis (w) =", w * 180/m.pi)

e_f = evec@rvec
if np.dot(rvec,vvec) > 0:
    f = m.acos(e_f/(emag*np.linalg.norm(rvec)))
else:
    f = 2*m.pi - m.acos(e_f/(emag*np.linalg.norm(rvec)))
print("True anomaly at epoch (f) =",f * 180/m.pi)



angular vel vec= [ 17090.8557 -24719.0051  14901.9625]
nmag = 30052.064183547333
Normal Vec = [24719.0051 17090.8557    -0.    ]
rmag = 7406.398348725243
vmag = 7.8360777178381795
eccentricity vec = [-0.06224701 -0.45333255 -0.68058653]
eccentricity mag = 0.8201116544275218

a = 8621.631561241436

angle of inclination (i) = 63.6244971105035
OMEGA angle = 34.66019451364651
argument of periapsis (w) = 247.86465714976347
True anomaly at epoch (f) = 138.9909304764967
